logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 8090
pandemic:
  social-search:
  service-url: http://api.social-searcher.com/v2/search?q
  api-key1: 1a8030fe42c457fe106442e71faeb074
  api-key2:
  search-keyword: corona OR covid19 OR fever
  
    
         