env: local
server:
  port: 8090
spring:
  datasource:
    driverClassName: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50000/BLUDB
    username: hms96093
    password: bs-1s495k1zchdzr
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.DB2Dialect
      ddl-auto: 
pandemic:
  social-search:
    service-url: http://api.social-searcher.com/v2/search
    api-key1: 1608b1d406a6f895f7c683a98953be6c
    api-key2: 1a8030fe42c457fe106442e71faeb074
    search-keyword: corona virus OR covid19
  ibm-nlu:
    service-url: https://api.eu-gb.natural-language-understanding.watson.cloud.ibm.com/instances/b3736d00-1f58-487a-905b-701f723c3faa
    api-key: LVuxollv9MZQD56_Tx8Jvtttt8xV9iiN05tLTAsbOWNl